export const AUTH_FAILED = 'AUTHENTICATION FAILED';
export const AUTH_SUCCESS = 'AUTHENTICATION WAS SUCCESSFULL';
export const AUTH_SERV_UNAVAILABLE = 'AUTHENTICATION IS NOT AVAILABLE!';
export const AUTH_PENDING = 'AUTHENTIFICATION IN PROGRESS';
export const LOGOUT = 'LOGOUT';
